# Generated by Django 5.2.1 on 2025-10-23 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
