"""
Django settings for gym_power project.

Generated by 'django-admin startproject' using Django 5.2.5.
"""

from pathlib import Path
import os

# --- Rutas base ---
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Seguridad ---
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure--u!3!_*(5#c3vp3us+%8ae*is%m^@r=en-3unde^$1u(_g6m*s')
DEBUG = True  # ⚠️ Solo para desarrollo

# --- Hosts permitidos ---
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '[::1]',
    '.ngrok-free.app',   # dominios ngrok nuevos
    '.ngrok-free.dev',   # dominios ngrok antiguos
]

# --- Aplicaciones instaladas ---
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user',
    'clases',
    'gym_power',
    'rest_framework',
    'django_filters',
]

# --- Middleware ---
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gym_power.urls'

# --- Templates ---
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # útil si luego usas HTML personalizado
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gym_power.wsgi.application'

# --- Base de datos ---
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'gymdb',
        'USER': 'admin',
        'PASSWORD': 'Gym2025@',
        'HOST': 'localhost',  # o 'db' si el servicio de Postgres está en Docker
        'PORT': '5432',
    }
}

# --- Validación de contraseñas ---
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --- Internacionalización ---
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --- Archivos estáticos ---
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # opcional, si usas /static localmente
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# --- Configuración de Login/Logout ---
LOGIN_REDIRECT_URL = '/home/'
LOGOUT_REDIRECT_URL = '/login/'

# --- CSRF y Seguridad ---
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'https://*.ngrok-free.app',
    'https://*.ngrok-free.dev',
]

CSRF_COOKIE_SECURE = False     # True solo en producción HTTPS
SESSION_COOKIE_SECURE = False
CSRF_USE_SESSIONS = False

# --- Telegram ---
TELEGRAM_BOT_TOKEN = "8216061394:AAFIqNZyBOU7O79HHSpnxSzX-buu26gfPgY"

# --- Configuración adicional ---
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Configuración de Correo ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'davidgonzalz0690@gmail.com'     
EMAIL_HOST_PASSWORD = 'ielu xvgq kywq raqa'  
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
